"""Verify the saved data and small-matrix identities, then build the internal note.

Run: OPENBLAS_NUM_THREADS=1 python build_note.py
Only generated files in this note directory are written; campaigns are read-only.
"""
from pathlib import Path
import csv
import hashlib
import itertools
import json
import re
import shutil
import subprocess

from pypdf import PdfReader
import numpy as np
from scipy.linalg import expm
from scipy.optimize import linear_sum_assignment

HERE = Path(__file__).resolve().parent
REPO = next(p for p in HERE.parents if (p / 'PROJECT_ADMIN/REPO_POLICY.md').is_file())
CAMPAIGN = REPO / '00_WORKSPACE/CURRENT/matched_markov_lindblad_campaign'
DATA = CAMPAIGN / 'steady_purity_gap_v1/results/20261005T184136Z'
STEM = 'channel_gap_discussion'


def sha(path):
    h = hashlib.sha256()
    with Path(path).open('rb') as f:
        for part in iter(lambda: f.read(1024 * 1024), b''):
            h.update(part)
    return h.hexdigest()


def verified_receipt(folder):
    receipt = folder / 'completion.json'
    rec = json.loads(receipt.read_text())
    assert rec['status'] == 'complete', receipt
    result = folder / rec['result_filename']
    assert result.stat().st_size == rec['result_bytes'], result
    assert sha(result) == rec['result_sha256'], result
    return rec, result


def verify_data():
    rows = list(csv.DictReader((DATA / 'analysis/gaps.csv').open()))
    assert len(rows) == 10
    records, indexed = [], {}
    for row in rows:
        alpha, ny = int(row['alpha_1']), int(row['Ny'])
        assert (alpha, ny) not in indexed
        folder = DATA / f'alpha{alpha}_Ny{ny:03d}'
        rec, result = verified_receipt(folder)
        cfg = rec['config']
        assert cfg['alpha_1'] == alpha and cfg['Ny'] == ny and cfg['Nx'] == 20
        assert cfg['cycles'] == 61 and cfg['sequence'] == 'raster_y'
        assert cfg['all_slabs_active'] and cfg['dw_truncation']
        assert rec['diagnostics']['converged']
        spectral_folder = Path(rec['spectral_reference']['folder'])
        spectral_rec, spectral_result = verified_receipt(spectral_folder)
        assert sha(spectral_folder / 'completion.json') == rec['spectral_reference']['receipt_sha256']
        assert sha(spectral_result) == rec['spectral_reference']['spectrum_sha256']
        for source, digest in spectral_rec['sources'].items():
            assert rec['sources'][source] == digest
        radius = spectral_rec['diagnostics']['spectral_radius']
        np.testing.assert_allclose(float(row['channel_gap']), 1 - radius ** 2, rtol=0, atol=1e-13)
        with np.load(result, allow_pickle=False) as z:
            assert z['observation_cycles'][-2:].tolist() == [60, 61]
            purity = np.min(np.abs(1 - 2 * z['occupations_full'][-1]))
            twirl = np.min(np.abs(1 - 2 * z['occupations_ky_twirl'][-1]))
            np.testing.assert_allclose(purity, float(row['purity_gap_full']), rtol=0, atol=1e-13)
            np.testing.assert_allclose(twirl, float(row['purity_gap_twirl']), rtol=0, atol=1e-13)
            assert np.max(z['successive_frobenius_change'][-5:]) < 1e-10
            assert abs(z['purity_gap_full'][-1] - z['purity_gap_full'][-2]) < 2e-10
            assert abs(z['purity_gap_twirl'][-1] - z['purity_gap_twirl'][-2]) < 2e-10
        indexed[(alpha, ny)] = row
        records.append(dict(case=folder.name, receipt_sha256=sha(folder / 'completion.json'),
                            result_sha256=rec['result_sha256'], spectral_receipt_sha256=sha(
                                spectral_folder / 'completion.json')))
    lines = []
    for ny in [20, 40, 60, 80, 100]:
        values = [indexed[(a, ny)][k] for a in [1, 3]
                  for k in ['channel_gap', 'purity_gap_full']]
        lines.append(str(ny) + ' & ' + ' & '.join(f'{float(v):.6f}' for v in values) + r' \\')
    (HERE / 'results_table.tex').write_text('% Generated by build_note.py from verified results.\n'
                                          + '\n'.join(lines) + '\n')
    return records


def superop(kraus):
    return sum(np.kron(k.conj(), k) for k in kraus)


def dissipator(k):
    ident = np.eye(k.shape[0])
    n = k.conj().T @ k
    return np.kron(k.conj(), k) - (np.kron(ident, n) + np.kron(n.T, ident)) / 2


def spectrum_error(actual, expected):
    distances = abs(np.asarray(actual)[:, None] - np.asarray(expected)[None, :])
    ii, jj = linear_sum_assignment(distances)
    return float(np.max(distances[ii, jj]))


def check_math():
    rng = np.random.default_rng(20261005)
    n, d = 3, 8
    annihilators = []
    for i in range(n):
        c = np.zeros((d, d), complex)
        for state in range(d):
            if state & (1 << i):
                c[state ^ (1 << i), state] = (-1) ** ((state & ((1 << i) - 1)).bit_count())
        annihilators.append(c)
    ident = np.eye(d)
    s_total, a_total = np.eye(d * d), np.eye(n)
    raw = rng.normal(size=(d, d)) + 1j * rng.normal(size=(d, d))
    rho = raw @ raw.conj().T
    rho /= np.trace(rho)

    def correlation(state):
        return np.array([[np.trace(state @ ci.conj().T @ cj)
                          for cj in annihilators] for ci in annihilators])

    errors = {}
    for j, target in enumerate([0, 1, 0, 1, 1, 0, 1]):
        v = rng.normal(size=n) + 1j * rng.normal(size=n)
        v /= np.linalg.norm(v)
        c = sum(x * op for x, op in zip(v, annihilators))
        number = c.conj().T @ c
        jump = c.conj().T if target else c
        kraus = [jump, number if target else ident - number]
        sj = superop(kraus)
        errors[f'reset_Id_plus_L_{j}'] = float(np.max(abs(
            sj - np.eye(d * d) - dissipator(jump) - dissipator(number))))
        p = np.outer(v, v.conj())
        q = np.eye(n) - p
        actual = sum(k @ rho @ k.conj().T for k in kraus)
        errors[f'covariance_reset_{j}'] = float(np.max(abs(
            correlation(actual) - q @ correlation(rho) @ q - target * p)))
        rho = actual
        s_total = sj @ s_total
        a_total = q @ a_total
    aeig = np.linalg.eigvals(a_total)
    radius = max(abs(aeig))
    neutral = [i + d * j for j in range(d) for i in range(d)
               if i.bit_count() == j.bit_count()]
    even = [i + d * j for j in range(d) for i in range(d)
            if (i.bit_count() - j.bit_count()) % 2 == 0]
    expected = []
    for p in range(n + 1):
        products = [np.prod(aeig[list(indices)]) for indices in itertools.combinations(range(n), p)]
        expected.extend(x * y.conjugate() for x in products for y in products)
    errors['complete_neutral_hierarchy_spectrum'] = spectrum_error(
        np.linalg.eigvals(s_total[np.ix_(neutral, neutral)]), expected)
    for label, indices, expected_r in [('neutral', neutral, radius**2), ('even', even, radius**2),
                                       ('unrestricted', list(range(d*d)), radius)]:
        eig = np.linalg.eigvals(s_total[np.ix_(indices, indices)])
        stationary = int(np.argmin(abs(eig - 1)))
        errors[label + '_stationary_eigenvalue'] = float(abs(eig[stationary] - 1))
        eig = np.delete(eig, stationary)
        errors[label + '_spectral_radius'] = float(abs(max(abs(eig)) - expected_r))
        if label == 'even':
            for p in [0.03, 0.2, 1.0]:
                errors[f'poisson_gap_p{p}'] = float(abs(1 - max(abs(1 - p + p*eig))
                                                       - p*(1 - radius**2)))
            errors['poisson_generator_gap'] = float(abs(min(1-eig.real) - (1-radius**2)))
    # Global maximally mixed replacement: every traceless multiplier is 1-p.
    t = np.outer((ident/d).reshape(-1, order='F'), ident.reshape(-1, order='F'))
    p = 0.37
    errors['global_depolarizing_spectrum'] = spectrum_error(
        np.linalg.eigvals((1-p)*np.eye(d*d)+p*t), [1]+[1-p]*(d*d-1))
    errors['global_poisson_semigroup'] = float(np.max(abs(
        expm(0.7*(t-np.eye(d*d))) - t - np.exp(-0.7)*(np.eye(d*d)-t))))
    # Local qubit depolarization, checked on the complete two-qubit operator space.
    paulis = [np.array([[0, 1], [1, 0]]), np.array([[0, -1j], [1j, 0]]), np.diag([1, -1])]
    local_l = sum(dissipator(np.kron(pauli, np.eye(2))) / 4
                  + dissipator(np.kron(np.eye(2), pauli)) / 4 for pauli in paulis)
    errors['local_depolarizing_spectrum'] = spectrum_error(
        np.linalg.eigvals(local_l), [0]+[-1]*6+[-2]*9)
    c = np.array([[0, 1], [0, 0]])
    errors['balanced_fermionic_spectrum'] = spectrum_error(
        np.linalg.eigvals(dissipator(c) + dissipator(c.T)), [0, -1, -1, -2])
    assert max(errors.values()) < 1e-11, errors
    return dict(test_count=len(errors), maximum_error=max(errors.values()), errors=errors)


def build():
    records, maths = verify_data(), check_math()
    build_dir = HERE / 'build'
    build_dir.mkdir(exist_ok=True)
    for _ in range(3):
        subprocess.run(['pdflatex', '-interaction=nonstopmode', '-halt-on-error',
                        '-output-directory=build', STEM + '.tex'], cwd=HERE,
                       check=True, capture_output=True)
    log = (build_dir / (STEM + '.log')).read_text()
    problems = [line for line in log.splitlines() if any(s in line for s in
                ['Overfull', 'undefined references', 'undefined citations', 'multiply defined',
                 'Token not allowed in a PDF string'])]
    assert not problems, problems
    shutil.copy2(build_dir / (STEM + '.pdf'), HERE / (STEM + '.pdf'))
    doc = PdfReader(HERE / (STEM + '.pdf'))
    links = [item.get_object() for page in doc.pages for item in page.get('/Annots', [])]
    uris = sorted(set(str(link['/A']['/URI']) for link in links
                      if '/A' in link and '/URI' in link['/A']))
    assert len([u for u in uris if u.startswith('https://')]) >= 23
    preview = HERE / 'preview'
    preview.mkdir(exist_ok=True)
    for i, page in enumerate(doc.pages, 1):
        assert page.extract_text().strip(), i
    subprocess.run(['pdftoppm', '-r', '90', '-png', str(HERE / (STEM + '.pdf')),
                    str(preview / 'page')], check=True, capture_output=True)
    source = (HERE / (STEM + '.tex')).read_text()
    assert len(re.findall(r'\\bibitem\{', source)) == 12
    record = dict(dataset=str(DATA.relative_to(REPO)), verified_cases=records,
                  mathematical_checks=maths, pages=len(doc.pages), hyperlinks=uris,
                  bibliography_entries=12, latex_layout_errors=problems,
                  build_command='OPENBLAS_NUM_THREADS=1 python build_note.py',
                  sha256={name: sha(HERE / name) for name in
                          [STEM+'.tex', STEM+'.pdf', 'results_table.tex', 'build_note.py']})
    (HERE / 'validation.json').write_text(json.dumps(record, indent=2)+'\n')
    print(json.dumps({k: record[k] for k in ['pages', 'bibliography_entries', 'latex_layout_errors']}, indent=2))
    print('Verified 10 campaign outputs, 10 matched spectral outputs, and', maths['test_count'],
          'small-matrix identities; maximum error:', maths['maximum_error'])


if __name__ == '__main__':
    build()
